region               = "ap-south-1"
environment          = "dev"
db_instance_class    = "db.t2.micro"
storage_type         = "gp2"
parameter_group_name = "default.postgres12"
engine_version       = "12.5"
engine               = "postgres"